### ISSUE TITLE
hi, could you upload answers to that course?

### ISSUE THREAD

**Issue by mtumilowicz** [uberto/funpatterns-longcourse#1]
I suggest doubling existing classes into something like:
- `CurryingWorkshop.kt` (it is equivalent of already existing `Currying.kt`)
- `CurryingAnswer.kt` - copy of `CurryingWorkshop.kt` but correctly solved

it's very ofter hard to tell what should I do event with tests...

i've prepared vavr workshops in the very that manner: [java11-vavr093-workshops](https://github.com/mtumilowicz/java11-vavr093-workshops) and it works great

**Comment by uberto** [comment]
Hi, the answers are in the solution branch.
Btw it's still a work in progress between one course and the next :)

**Comment by mtumilowicz** [comment]
great! so im looking forward to the final version!
